# Generated by Django 3.2.6 on 2021-09-13 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('symbol_id', models.CharField(max_length=100)),
                ('container_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('interest_users', models.ManyToManyField(blank=True, related_name='interest_stock', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
