# Generated by Django 3.2.6 on 2021-08-23 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('open', models.IntegerField(null=True)),
                ('high', models.IntegerField(null=True)),
                ('low', models.IntegerField(null=True)),
                ('close', models.IntegerField(null=True)),
                ('vol', models.IntegerField(null=True)),
                ('value', models.IntegerField(null=True)),
                ('n_stock', models.IntegerField(null=True)),
                ('agg_price', models.IntegerField(null=True)),
                ('foreign_rate', models.FloatField(null=True)),
                ('interest_users', models.ManyToManyField(blank=True, related_name='interst_stock', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
